[gamepad]
# XInput 手柄编号：0~3
index = 0

# 手柄扫描频率
poll_hz = 120


[throttle]
# 普通模式短按一次发送多少次 THROTTLE_INCR / THROTTLE_DECR
tap_count = 3

# 普通模式长按后，每秒发送多少次事件
hold_send_hz = 24

# 按下多久后进入长按连续模式，单位：秒
hold_delay = 0.28


[fine_throttle]
# 是否启用 LB + A/B 微调模式
enabled = true

# 微调模式短按一次发送多少次 THROTTLE_INCR_SMALL / THROTTLE_DECR_SMALL
fine_tap_count = 2

[brake]
# 功能开关
enabled = true

# 轻按一次增加的百分比 (%)
tap_increase = 15.0

# 长按增加的速率 (%/s)
hold_increase_per_sec = 0.0

# 衰减延迟 (s)
decay_delay = 0.28

# 衰减速率（%/s)
decay_per_sec = 120.0